# Generated by Django 2.2.24 on 2023-11-08 20:12

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber


COUNTRY = 'RU'


def convert_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator(chunk_size=1000): # Use this filter for testing: filter(owners_phonenumber='+70000000000'):
        num = PhoneNumber.from_string(flat.owners_phonenumber, COUNTRY)
        if num.is_valid():
            flat.owner_pure_phone = num.as_e164
        else:
            flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231108_1546'),
    ]

    operations = [
        migrations.RunPython(convert_phonenumbers)
    ]
