# Generated by Django 2.2.24 on 2023-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231110_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(max_length=20, verbose_name='Номер владельца'),
        ),
    ]
