# Generated by Django 2.2.24 on 2023-11-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_create_flats_owners_relations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='owner_deprecated',
        ),
    ]
