# Generated by Django 2.2.24 on 2023-11-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20231110_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
    ]
