# Generated by Django 2.2.24 on 2023-11-10 19:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20231110_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Номер владельца'),
        ),
    ]
